FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /interest-rate
   
# copy source
COPY . .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /interest-rate   
COPY --from=build /interest-rate/out ./

ENTRYPOINT ["dotnet", "Soft.InterestRate.Api.dll"]