FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /calculate-interest
   
# copy source
COPY . .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /calculate-interest   
COPY --from=build /calculate-interest/out ./

ENV APIURL http://localhost:8200/api/TaxaJuros

ENTRYPOINT ["dotnet", "Soft.CalculateInterest.Api.dll"]