FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /api2
   
# copy source
COPY . .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /api1   
COPY --from=build /api2/out ./

ENV APIURL http://localhost:8100/api/TaxaJuros

ENTRYPOINT ["dotnet", "API 2.dll"]